source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'JoinComments' do
	use_modular_headers!
	pod 'AFNetworking', '3.2.1'
	pod 'SDWebImage', '~> 5.6.0'
	pod 'MBProgressHUD', '~> 1.2.0'
	pod 'MJRefresh', '~> 3.3.1'
  pod 'IQKeyboardManager', '~> 6.5.5'
  pod "dsBridge", '~> 3.0.6'

end

